#服务名称
server:
  port: 8082

#连接配置信息
spring:
  #  jackson:
  #   serialization:
  #    FAIL_ON_EMPTY_BEANS: false
  application:
    name: lezu_consumer_server
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        default-label: dev
        jdbc:
          sql: SELECT akey , avalue FROM config_server where APPLICATION=? and APROFILE=? and LABEL=?
  #####################################################################################################
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.150.130:3306/lezuConsumer
    username: root
    password: 123456
#####################################################################################################

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://121.196.150.130:8765/eureka/
mybatis-plus:
  mapper-locations: classpath:/cn/lezu/consumer/mapper/*.xml
  config-location: classpath:/mybatis-config.xml